### ISSUE TITLE
time zones abbreviations are not supported

### ISSUE THREAD

**Issue by KalachevDev** [gravity-ui/date-utils#25]
there is a difference between moment and dayjs APIs

`dayjs().tz('Europe/Moscow').format('z') // 'GMT+3’`
`moment(Date.now()).tz('Europe/Moscow').zoneAbbr() // 'MSK’`

it seems that it could be a good feature to support timezones abbreviations

I think we can extend dayjs functionality by adding some flag: `abbreviateTimezone: true/false` and overriding `.format()` method as following:
`format('z')` returns `GMT +3`, after that if abbreviateTimezone flag is turned on, we search through the result string and replace `GMT +3` with provided abbreviations

date-utils itself could provide some default abbreviations, like `GMT +3 = MSK`, however it would be great to have an ability to override default abbreviations

**Comment by korvin89** [comment]
These alphabetic abbreviations [are not part of the international time and date standard](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) and due to this fact we are not considering adding such formatting for now.
