### ISSUE TITLE
Breaks production build

### ISSUE THREAD

**Issue by krendeleno** [gravity-ui/date-utils#32]
My project stack:
- Next 13.4.3
- React 18.2.0

When i try to import @gravity-ui/date-utils in dev everything works fine, but production build breaks with these errors:

<img width="949" alt="image" src="https://github.com/gravity-ui/date-utils/assets/63800083/a7315b47-a698-4c4e-b327-ab025d04af17">

**Comment by ValeraS** [comment]
Hi, can you please provide [codesandbox](https://codesandbox.io) with reproduction of this error?

**Comment by krendeleno** [comment]
I've researched the issue and found out that my project was duplicating the packages with date-utils. Errors were caused by import of dayjs, so I've installed this package separately and set up the alias in the webpack config - this resolved the problem! 🎉
