### ISSUE TITLE
The ability to parse the date and time in UTC format

### ISSUE THREAD

**Issue by kuzmadom** [gravity-ui/date-utils#49]
It would be useful to have a utility for working with the date in utc format. Something like the old version of working with a date or an analog in [dayjs](https://day.js.org/docs/en/plugin/utc):

```
dayjs.utc('2023-12-31'); // '2023-12-31T00:00Z'
dayjs.utc('2023-12-31T00:00Z'); // '2023-12-31T00:00Z'
```

**Comment by korvin89** [comment]
@ValeraS Hey! Do you know how can we handle this case?
