### ISSUE TITLE
When you select the time zone parsing works incorrectly

### ISSUE THREAD

**Issue by kseniya57** [gravity-ui/date-utils#58]
I selected Europe/Moscow time zone and tried to enter 12.03.2023, but the result was 12.02.2023

https://github.com/gravity-ui/date-utils/assets/31247233/f98d3328-fd5d-4300-b6df-09645a2d9c4e

**Comment by korvin89** [comment]
Fixed here https://github.com/gravity-ui/date-utils/releases/tag/v2.5.0
