### ISSUE TITLE
How to create DateTime with specific time and time zone?

### ISSUE THREAD

**Issue by lxndr** [gravity-ui/date-utils#70]
Hello!

For example, I got '2024-01-01' and 'Europe/Moscow' and I want DateTime to be '2024-01-01T00:00:00+03:00'. Any way I could achieve this with dateTimeParse?

**Comment by ValeraS** [comment]
You can use `dateTimeUtc` like this:
```js
dateTimeUtc({input: '2024-01-01'}).timeZone('Europe/Moscow', true)
```

**Comment by lxndr** [comment]
Thanks a lot!
